#!/bin/bash
set -e

#PHP_ERROR_REPORTING=${PHP_ERROR_REPORTING:-"E_ALL"}
sed -ri 's/^display_errors\s*=\s*Off/display_errors = On/g' /etc/php/7.2/apache2/php.ini
sed -ri 's/^display_errors\s*=\s*Off/display_errors = On/g' /etc/php/7.2/cli/php.ini
sed -ri "s/^error_reporting\s*=.*$//g" /etc/php/7.2/apache2/php.ini
sed -ri "s/^error_reporting\s*=.*$//g" /etc/php/7.2/cli/php.ini
echo "error_reporting = $PHP_ERROR_REPORTING" >> /etc/php/7.2/apache2/php.ini
echo "error_reporting = $PHP_ERROR_REPORTING" >> /etc/php/7.2/cli/php.ini

if [ "$ALLOW_OVERRIDE" = "**False**" ]; then
    unset ALLOW_OVERRIDE
else
    sed -i "s/AllowOverride None/AllowOverride All/g" /etc/apache2/apache2.conf
    a2enmod rewrite
fi

composer install --no-interaction
source /etc/apache2/envvars && exec /usr/sbin/apache2 -DFOREGROUND